src/StudyProject.UI.Web/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using StudyProject.Domain.Security;
using StudyProject.UI.WebCore.Extensions;

namespace StudyProject.UI.WebCore.Controllers
{
    [AuthorizeEnum(RoleAuthorize.Admin, RoleAuthorize.Client)]
    public class ClientController : Controller
    {
        [AuthorizePolicyEnum(PERMISSIONS.Read)]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/StudyProject.UI.Web/Controllers/ProductController.cs
using CategoriasMvc.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StudyProject.Application.Identity.AccountViewModels;
using StudyProject.Application.ViewModels;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace StudyProject.UI.WebCore.Controllers
{
    // [AuthorizeEnum(RoleAuthorize.Admin, RoleAuthorize.Manager)]
    public class ProductController : Controller
    {
        private readonly IProdutoService _produtoService;
        private readonly IAutenticacao _autenticacaoService;
        private string token = string.Empty;
        public ProductController(IProdutoService produtoService, IAutenticacao autenticacaoService)
        {
            _autenticacaoService = autenticacaoService;
            _produtoService = produtoService;
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginViewModel model)
        {
            //verifica se o modelo é válido
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Login Inválido....");
                return View(model);
            }
            //verifica as credenciais do usuário e retorna um valor
            var result = await _autenticacaoService.AutenticaUsuario(model);


            if (result is null)
            {
                ModelState.AddModelError(string.Empty, "Login Inválido....");
                return View(model);
            }

            HttpContext.Response.Cookies.Append("X-Access-Token", result.Token, new CookieOptions()
            {
                Secure = true,
                HttpOnly = true,
                SameSite = SameSiteMode.Strict,
                IsEssential = true
            });
            return Redirect("Home/Index");

        }

        //[AuthorizePolicyEnum(PERMISSIONS.Index)]
        [HttpGet]
        public async Task<ActionResult<IEnumerable<ProductVM>>> Index()
        {
            //extrai o token do cookie
            var result = await _produtoService.GetProdutos(ObtemTokenJwt());

            if (result is null)
                return View("Error");

            return View(result);
        }

        private string ObtemTokenJwt()
        {
            if (HttpContext.Request.Cookies.ContainsKey("X-Access-Token"))
                token = HttpContext.Request.Cookies["X-Access-Token"].ToString();

            return token;
        }
    }
}

src/StudyProject.UI.Web/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StudyProject.Domain.Identity;
using StudyProject.Domain.Security;
using StudyProject.UI.WebCore.Extensions;
using StudyProject.UI.WebCore.Models;

namespace StudyProject.UI.WebCore.Controllers
{
        public class RoleController : Controller
        {
            private readonly RoleManager<ApplicationRole> _roleManager;
            private readonly UserManager<ApplicationUser> _userManager;

            public RoleController(RoleManager<ApplicationRole> roleManager, UserManager<ApplicationUser> userManager)
            {
                _roleManager = roleManager;
                _userManager = userManager;
            }

            public IActionResult Index()
            {
                RoleViewModel rolesToUsersViewModel = new RoleViewModel();
                rolesToUsersViewModel.AllRoles = PolicyTypes.ListAllRoles
                                           .Select(role => new SelectListItem
                                           {
                                               Value = role,
                                               Text = role
                                           }).ToList();
                rolesToUsersViewModel.AllClaims = PolicyTypes.ListClaimsAuthorizations
                               .Select(claim => new SelectListItem
                               {
                                   Value = claim,
                                   Text = claim
                               }).ToList();
                return View(rolesToUsersViewModel);
            }

            public IActionResult Create()
            {
                var role = new ApplicationRole();
                return View(role);
            }

            [HttpPost]
            public async Task<IActionResult> Create(ApplicationRole role)
            {
                IdentityResult roleResult;
                //Adding Admin Role
                var roleCheck = await _roleManager.RoleExistsAsync(role.Name);
                if (!roleCheck)
                {
                    //create the roles and seed them to the database
                    roleResult = await _roleManager.CreateAsync(role);
                }

                return RedirectToAction("Index");
            }

            public IActionResult AssignRoleToUser()
            {
                RoleViewModel rolesToUsersViewModel = new RoleViewModel();

                rolesToUsersViewModel.AllRoles = _roleManager.Roles.ToList()
                                                       .Select(role => new SelectListItem
                                                       {
                                                           Value = role.Id.ToString(),
                                                           Text = role.Name
                                                       }).ToList();

                rolesToUsersViewModel.AllUsers = _userManager.Users.ToList()
                                                       .Select(user => new SelectListItem
                                                       {
                                                           Value = user.Id.ToString(),
                                                           Text = user.UserName
                                                       }).ToList();

                return View(rolesToUsersViewModel);
            }

            [HttpPost]
            public async Task<IActionResult> AssignRoleToUser(RoleViewModel rolesToUsersViewModel)
            {
                // ViewData["ReturnUrl"] = returnUrl;
                if (ModelState.IsValid)
                {
                    var user = await _userManager.FindByIdAsync(rolesToUsersViewModel.UserSelected);

                    var result = await _userManager.AddToRoleAsync(user, rolesToUsersViewModel.RoleSelected);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    // AddErrors(result);
                }

                // If we got this far, something failed, redisplay form
                return RedirectToAction("Index");
            }

            [HttpGet]
            public IActionResult GetAjaxHandlerRoles(string userID)
            {
                var user = _userManager.FindByIdAsync(userID).Result;
                RoleViewModel rolesToUsersViewModel = new RoleViewModel();

                rolesToUsersViewModel.AllRoles = _roleManager.Roles.ToList()
                                                       .Select(role => new SelectListItem
                                                       {
                                                           Value = role.Id.ToString(),
                                                           Text = role.Name
                                                       }).ToList();

                var rolesSelectedNames = _userManager.GetRolesAsync(user).Result;

                rolesToUsersViewModel.AllRoles = rolesToUsersViewModel.AllRoles.Select(x => { x.Selected = rolesSelectedNames.Any(r => r.Equals(x.Text)); return x; }).ToList();
                return Json(rolesToUsersViewModel.AllRoles);
            }

            [HttpPost]
            public IActionResult PostAjaxHandlerRoles(string[] rolesJSON, string userID)
            {
                Guid id;

                if (Guid.TryParse(userID, out id))
                {
                    var user = _userManager.Users.Where(u => u.Id.ToString() == userID).Include(x => x.UserRoles).FirstOrDefault();
                    var rolesExists = user.UserRoles;

                    JsonSerialize jsonS = new JsonSerialize();
                    var rolesVM = jsonS.JsonDeserializeObject<List<DropDpwnViewModel>>(rolesJSON[0]);
                    var appUsersRolesToRemove = rolesExists.Where(x => !rolesVM.Any(z => z.id == x.RoleId.ToString())).ToList();

                    IdentityResult result;

                    var rolesToAdd = rolesVM.Where(x => !rolesExists.Any(z => z.RoleId.ToString() == x.id)).ToList();
                    if (rolesToAdd.Count > 0)
                        result = _userManager.AddToRolesAsync(user, rolesToAdd.Select(x => x.text).ToArray()).Result;

                    if (appUsersRolesToRemove.Count > 0)
                    {
                        var rolesNameToRemove = _roleManager.Roles.Where(x => appUsersRolesToRemove.Any(z => z.RoleId == x.Id)).Select(x => x.Name).ToList();
                        if (rolesNameToRemove.Count > 0)
                            result = _userManager.RemoveFromRolesAsync(user, rolesNameToRemove).Result;
                    }
                    return Json(new { OK = "ok" });
                }
                else
                {
                    return Json(new { OK = "Without user" });
                }
            }

            [HttpPost]
            public IActionResult PostAjaxHandlerClaimsToRole(string[] claimsJSON, string roleID)
            {
                Guid id;

                if (Guid.TryParse(roleID, out id))
                {
                    var role = _roleManager.Roles.Where(r => r.Id == id).Include(c => c.RoleClaims).FirstOrDefault();
                    var rolesExists = role.RoleClaims;

                    JsonSerialize jsonS = new JsonSerialize();
                    var claimsVM = jsonS.JsonDeserializeObject<List<DropDpwnViewModel>>(claimsJSON[0]);
                    var appRolesClaimsToRemove = rolesExists.Where(x => !claimsVM.Any(z => z.id == x.ClaimValue.ToString())).ToList();

                    var claimsToAdd_VMs = claimsVM.Where(x => !rolesExists.Any(z => z.ClaimValue == x.id)).ToList();
                    if (claimsToAdd_VMs.Count > 0)
                    {
                        var claimsAdd = PolicyTypes.ListAllClaims.Where(x => claimsToAdd_VMs.Any(c => c.id == x.Value.Value)).Select(x => x.Value).ToList();
                        foreach (var item in claimsAdd)
                        {
                            var result = _roleManager.AddClaimAsync(role, item);
                            result.Wait();
                        }
                    }

                    if (appRolesClaimsToRemove.Count > 0)
                    {
                        var claims = _roleManager.GetClaimsAsync(role).Result;
                        var claimsToRemove = claims.Where(x => appRolesClaimsToRemove.Any(z => z.ClaimValue == x.Value)).ToList();

                        if (claimsToRemove.Count > 0)
                        {
                            foreach (var item in claimsToRemove)
                            {
                                var result = _roleManager.RemoveClaimAsync(role, item);
                                result.Wait();
                            }
                        }
                    }

                    return Json(new { OK = "ok" });
                }
                else
                {
                    return Json(new { OK = "Without user" });
                }
            }
            [HttpGet]
            public IActionResult GetAjaxHandlerClaimsRoles(string roleID)
            {
                RoleViewModel rolesViewModel = new RoleViewModel();

                var rol = _roleManager.FindByIdAsync(roleID).Result;
                var claims = _roleManager.GetClaimsAsync(rol).Result;

                var claimsListItem = PolicyTypes.ListAllClaims
                                                     .Select(claim => new SelectListItem
                                                     {
                                                         Value = claim.Value.Value,
                                                         Text = claim.Value.Value

src/StudyProject.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Study Project</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/bower_components/Ionicons/css/ionicons.min.css">
    <link rel="stylesheet" href="~/bower_components/select2/dist/css/select2.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/dist/css/skins/skin-blue.min.css">
    <!-- jQuery 3 -->
    <script src="~/bower_components/jquery/dist/jquery.min.js"></script>

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="index2.html" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>AP</b>T</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>STUDY</b>PROJECT</span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="~/dist/img/user1.jpg" class="user-image" alt="User Image">
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">Hello @User.Identity.Name!</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="~/dist/img/user1.jpg" class="img-circle" alt="User Image">
                                    <p>
                                        Juliano Pestili - Developer
                                        <small>Member since jan. 2019</small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li class="user-body">
                                    <div class="row">
                                        <div class="col-xs-4 text-center">
                                            <a href="#">Account</a>
                                        </div>
                                    </div>
                                    <!-- /.row -->
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <form method="post" asp-controller="Account" asp-action="Logout">
                                            <input class="btn btn-default btn-flat" type="submit" value="Logout" />
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/dist/img/user1.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <p>Juliano Pestili</p>
                        <!-- Status -->
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
                <!-- search form (Optional) -->
                <form action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                </form>
                <!-- /.search form -->
                <!-- Sidebar Menu -->
                <partial name="~/Views/Shared/_MainMenu.cshtml" />
                <!-- /.sidebar-menu -->
            </section>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            @RenderBody()
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- Default to the left -->
            <strong>Copyright &copy; 2019 <a href="https://github.com/JulianoMuteki/StudyProject">StudyProject</a>.</strong> All rights reserved.
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED JS SCRIPTS -->
    <!-- Bootstrap 3.3.7 -->
    <script src="~/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- Select2 -->
    <script src="~/bower_components/select2/dist/js/select2.full.min.js"></script>

    <!-- DataTables -->
    <script src="~/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
    <script>
        $(function () {
            $('#vaccine').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        })
    </script>
</body>
</html>

src/StudyProject.UI.Web/Views/Shared/_LayoutClear.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Study Project</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="~/bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/AdminLTE.min.css">
    <link rel="stylesheet" href="~/dist/css/skins/skin-blue.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/iCheck/square/blue.css">

    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

</head>
<body class="hold-transition login-page">
    <!-- /.login-box -->
    @RenderBody()

    <!-- jQuery 3 -->
    <script src="../../bower_components/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    <script src="../../plugins/iCheck/icheck.min.js"></script>
    <script>
$(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });</script>
</body>
</html>

src/StudyProject.UI.Web/Views/Shared/_MainMenu.cshtml
<ul class="sidebar-menu" data-widget="tree">
    <li class="header">HEADER</li>
    <!-- Optionally, you can add icons to the links -->
    <li class="active"><a href="#"><i class="fa fa-link"></i> <span>Link</span></a></li>
    <li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-pie-chart"></i>
            <span>Charts</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a asp-action="Index" asp-controller="Product"><i class="fa fa-circle-o"></i> Product Flot</a></li>
            <li><a asp-action="Index" asp-controller="Client"><i class="fa fa-circle-o"></i> Client Inline</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-user-secret"></i>
            <span>Security</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a asp-action="Index" asp-controller="Role"><i class="fa fa-circle-o"></i> Roles</a></li>
        </ul>
    </li>
    <li class="treeview">
        <a href="#">
            <i class="fa fa-link"></i> <span>Multilevel</span>
            <span class="pull-right-container">
                <i class="fa fa-angle-left pull-right"></i>
            </span>
        </a>
        <ul class="treeview-menu">
            <li><a href="#">Link in level 2</a></li>
            <li><a href="#">Link in level 2</a></li>
        </ul>
    </li>
</ul>